baseURL = 'https://computercobbler.net/'
locale = 'en-us'
title = 'Computer Cobbler'
disableKinds = ['taxonomy', 'term']
buildFuture = true

[params]
  description = 'Quality goods, simply sold.'
  currency = '$'
  contactEmail = 'support@computercobbler.net'

[menus]
  [[menus.main]]
    name = 'Store'
    pageRef = '/products'
    weight = 10
  [[menus.main]]
    name = 'Events'
    pageRef = '/events'
    weight = 20
  [[menus.main]]
    name = 'About Us'
    pageRef = '/about'
    weight = 30
